# Generated by Django 4.1.1 on 2022-10-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='main_app.car'),
        ),
    ]
